### ISSUE TITLE
The input paramter name in readme should be namespace instead of name

### ISSUE THREAD

**Issue by dunmengjun** [okteto/namespace#1]
Since i use this action in my project, i got a warning
```
Warning: Unexpected input(s) 'name', valid inputs are ['entryPoint', 'args', 'namespace']
```
So i reviewed the code found in the action define file:

https://github.com/okteto/namespace/blob/1cb27522f16a4db1497f109dcbbab19af4756b6d/action.yml#L3-L7

but in the readme file is:
```
    - name: "Create devlopment environments namespace"
      uses: okteto/namespace@master
      with:
        name: devenvs-cindylopez
```
It's different. Although it does not affect anything, the program still works, but I think it is better to unify

I mentioned a pull request by the way: https://github.com/okteto/namespace/pull/2
